### ISSUE TITLE
Create Users:Mailaddress option

### ISSUE THREAD

**Issue by hanchenglin** [yasuflatland-lf/liferay-dummy-factory#11]
The current mailaddress domain is fixed liferay.com. 
Like Gmail  user+001@gmail.com,user+002@gmail.com ....  user+999@gmail.com are same user.
When testing mail sending, it is useful if tool can create option rule to generate a mail address.

Thank you very much!

**Comment by yasuflatland-lf** [comment]
Hi @hanchenglin , I added this functionality in 33ead80fcb70c6458a04c6a0a09b00bf28d1e8c8, will be released in the next version.
