### ISSUE TITLE
Progress bar runs even I don't enter required fields

### ISSUE THREAD

**Issue by nisarg34** [yasuflatland-lf/liferay-dummy-factory#21]
When I am creating any dummy data and click on Run without filling up mandatory information, UI shows correct messages but progress bar still continues to execute.

![image](https://user-images.githubusercontent.com/20126333/36579761-d5df7340-188a-11e8-8b92-b1c7a44de79d.png)

**Comment by yasuflatland-lf** [comment]
Fixed 669e5d0e012ca4519b590c96ee0f708a3a9c1936
