### ISSUE TITLE
It doesn't create categories, but shows successful message

### ISSUE THREAD

**Issue by ricardofunke** [yasuflatland-lf/liferay-dummy-factory#23]
In Liferay DXP de-32:

1) Select "Category / Vocabularies" as the data to create
2) Select "Liferay DXP" as the Site
3) Select "Topic" as the vocabulary id (it shows "Topic" twice)
4) Select "None" as the parent category id
5) Enter 10 for the number of categories to create
6) Enter "mycategory" as the base category name

After execution, it shows a successful message and the logs shows:
```
Starting to create 10 categories
Finished creating 10 categories
```
But in the categories screen, no categories are shown

If you try it again, it gives the error "There is another category named mycategory1 as a child of category 0"

Already tried to reindex all indexes, but still doesn't show the categories in the category screen

**Comment by ricardofunke** [comment]
It looks like it has something to do with the "Topic" selection, it shows twice and when I selected the one in the botton one, it works as expected.

**Comment by yasuflatland-lf** [comment]
@ricardofunke , thank you for this report. I'll look into it and fix it.
