### ISSUE TITLE
Move main selector to its own tab

### ISSUE THREAD

**Issue by jordirodo** [yasuflatland-lf/liferay-dummy-factory#25]
UX Improvement.

<img width="1440" alt="screenshot_2018-04-03_10_35_15" src="https://user-images.githubusercontent.com/8917703/38224441-fad02cf8-372a-11e8-91a5-ef7ab45cf504.png">

**Comment by jordirodo** [comment]
Or have its own sub-menu within the "Dummy Factory" product menu.

**Comment by yasuflatland-lf** [comment]
Since the number of functionality Dummy factory support could increase, layout showed won't be able to layout nicely. With that said, I'll keep the layout as it is.
