### ISSUE TITLE
Gradle assemble doesn't generate MANIFEST.MF correctly

### ISSUE THREAD

**Issue by rodrigopaulino** [yasuflatland-lf/liferay-dummy-factory#27]
When I run `gradle clean assemble` at the root folder of the repo, the built `build/libs/liferay-dummy-factory.jar` doesn't contain all the bundle's properties (i.e. Bundle-Name, Bundle-SymbolicName, Import-Package etc).
I'm using the gradle committed in this repo and I've tried with more than one branch: master, 7.1.x, tag/0.16.

**Comment by yasuflatland-lf** [comment]
@rodrigopaulino Thank you for reporting this. Let me confirm, does "'I'm using the gradle committed in this repo" means using ```gradlew clean assemble```?

**Comment by rodrigopaulino** [comment]
Yes. That is correct

**Comment by yasuflatland-lf** [comment]
@rodrigopaulino , please checkout 7.1.x and git id 19650d73c64238288a3b8ff0a64c279af196390a, and run ```gradlew clean assemble``` should create a bundle properly.

**Comment by rodrigopaulino** [comment]
Hey, @yasuflatland-lf.

I believe that you have to set the version of some dependencies for ones that are already released in `build.gradle`. See attached [log.txt](https://github.com/yasuflatland-lf/liferay-dummy-factory/files/2072722/log.txt)

**Comment by yasuflatland-lf** [comment]
@rodrigopaulino Please try this. I could successfully build and deploy with this steps below from scratch.
* Install Blade (https://dev.liferay.com/ja/develop/tutorials/-/knowledge_base/7-0/blade-cli)
* Clone liferay-portal repository, checkout master and run ```ant all```. It'll create ```bundles``` directory.
* Under the ${HOME}/.gradle and those missing jars should be created.
* Start up Liferay server under ```bundles``` directory that you just built.
* Go to the liferay workspace where dummy factory is placed and go to the dummy factory root directory and run ```blade deploy```.
