### ISSUE TITLE
Add option to never expire journal content

### ISSUE THREAD

**Issue by reizero00** [yasuflatland-lf/liferay-dummy-factory#33]
I was using dummy factory to test Apio by creating a ton of structured journal content. Journal content that was created are not set to "Never Expire" . In Apio, when I'm retrieving a collection of structured content, it will only return "Active" content in the response. 

It would be nice to be able to configure this on dummy factory :smile_cat:

**Comment by yasuflatland-lf** [comment]
@reizero00 On 7.2, looks like Never Expired and Never review are all enabled by default. So is it OK to add a feature to turn of each of them, and configure 1 month ahead date from the display date?
