### ISSUE TITLE
JournalStructureBaseDummyGenerator.updateArticle is no longer valid

### ISSUE THREAD

**Issue by janditibi** [yasuflatland-lf/liferay-dummy-factory#45]
Since https://liferay.atlassian.net/browse/LPS-192837 the parameter list is changed therefore journal generation fails with NoSuchMethodError

**Comment by yasuflatland-lf** [comment]
@janditibi Thank you for reporting this, so this change is since U92, isn't it?

**Comment by janditibi** [comment]
Yes, it changed since u92.

**Comment by yasuflatland-lf** [comment]
@janditibi kk, let me look at it.
