### ISSUE TITLE
Add random content to webcontents

### ISSUE THREAD

**Issue by vilmospapp** [yasuflatland-lf/liferay-dummy-factory#7]
For example based on http://lipsum.com the content could be different to simulate more realistic scenarios. Image and document links and embedded images from external url or from documents and media should be also handled.

**Comment by yasuflatland-lf** [comment]
Hi, @vilmospapp, the random contents generation and inserting random images functionality has implemented in e17d273b48a64390e596235a33c641fba6e9f611 .  
1. Navigate to configuration page of Dummy Factory
2. Type source site for images, (https://imgur.com/, for example). You can add multiple sites separated by comma, but it takes time. So recommend you to use 1 or 2 sites for the image source.
3. Wait the crawler generate links
4. Save it and go back to "Web Content Articles" page
5. Go option, check "Generate Fake Contents"
6. Set values in each field appropriately and run

**Comment by yasuflatland-lf** [comment]
Done on #be8cdf86378e6057c0d3219b4c6191d57efb6433
