### ISSUE TITLE
Add option to use DDMStructures and DDMTemplates for generated Web Contents

### ISSUE THREAD

**Issue by vilmospapp** [yasuflatland-lf/liferay-dummy-factory#8]
Existing Structures and Templates should be possible to use by Web Contents generated by the tool. Some issues come on surface related to content editing when specific structures are used.

**Comment by yasuflatland-lf** [comment]
Hi @vilmospapp 

I can add pull downs to let users select structures and templates. Is it ok just generating empty contents with the selected structure and template or, do you want to insert some contents into fields where you desire?

**Comment by vilmospapp** [comment]
Hi @yasuflatland-lf 

I think some precreated dummy structures and templates could be good and they should be prefilled with dummy content.

**Comment by yasuflatland-lf** [comment]
Hi @vilmospapp , Ok, so you mean providing pulldowns for selecting structure and a template is good enough?

**Comment by vilmospapp** [comment]
I think it should be enough.

**Comment by yasuflatland-lf** [comment]
@vilmospapp  Implemented in ef924427a62a4f2af450cdedb8a7a8208e93ce7c
